Repository CAUCSE/CAUSW_backend, pull requests merged in 2021-07, with the labels that each got.

#12 feat: Implement example
  src/main/java/net/causw/adapters/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserDetailDto.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
  src/main/java/net/causw/domain/spi/UserPort.java
  src/main/java/net/causw/infra/BaseEntity.java
  src/main/java/net/causw/infra/Role.java
  src/main/java/net/causw/infra/User.java
  src/main/java/net/causw/infra/UserRepository.java
  src/main/java/net/causw/infra/port/UserPortImpl.java
  src/main/resources/application.yaml
Labels: develop, enhancement

#13 chore: ci 기본적인 부분 우선 구성
  .github/workflows/ci.yml
Labels: develop, enhancement

#26 feat: impl user_auth_log entity
  src/main/java/net/causw/application/dto/UserDetailDto.java
  src/main/java/net/causw/infra/UserAuthLog.java
  src/main/java/net/causw/infra/UserAuthLogRepository.java
Labels: develop, enhancement

#32 fix: update user auth model
  src/main/java/net/causw/application/UserAuthService.java
  src/main/java/net/causw/application/dto/UserAuthDto.java
  src/main/java/net/causw/domain/spi/UserAuthPort.java
  src/main/java/net/causw/infra/UserAuth.java
  src/main/java/net/causw/infra/UserAuthRepository.java
  src/main/java/net/causw/infra/port/UserAuthPortImpl.java
  src/main/java/net/causw/web/UserController.java
Labels: develop, enhancement

#36 feat: Implement user sign up
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/UserAuthService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/BoardDetailDto.java
  src/main/java/net/causw/application/dto/PostDetailDto.java
  src/main/java/net/causw/application/dto/UserAuthDto.java
  src/main/java/net/causw/application/dto/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/UserDetailDto.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/main/java/net/causw/application/spi/UserAuthPort.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/main/java/net/causw/domain/model/BoardDomainModel.java
  src/main/java/net/causw/domain/model/PostDomainModel.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
  src/main/java/net/causw/domain/spi/BoardPort.java
  src/main/java/net/causw/domain/spi/PostPort.java
  src/main/java/net/causw/domain/spi/UserAuthPort.java
  src/main/java/net/causw/domain/spi/UserPort.java
  src/main/java/net/causw/infra/User.java
  src/main/java/net/causw/infra/port/BoardPortImpl.java
  src/main/java/net/causw/infra/port/PostPortImpl.java
  src/main/java/net/causw/infra/port/UserAuthPortImpl.java
  src/main/java/net/causw/infra/port/UserPortImpl.java
  src/main/java/net/causw/web/UserController.java
Labels: develop, enhancement

#43 fix: update circle model and user port impl, add illegal exception model
  src/main/java/net/causw/adapter/db/Circle.java
  src/main/java/net/causw/adapter/db/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/main/java/net/causw/config/SwaggerConfig.java
Labels: bug, develop, enhancement

#51 refac: Add student id column at User table
  src/main/java/net/causw/adapter/persistence/BaseEntity.java
  src/main/java/net/causw/adapter/persistence/Board.java
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/Circle.java
  src/main/java/net/causw/adapter/persistence/CircleRepository.java
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/PostRepository.java
  src/main/java/net/causw/adapter/persistence/User.java
  src/main/java/net/causw/adapter/persistence/UserAuth.java
  src/main/java/net/causw/adapter/persistence/UserAuthRepository.java
  src/main/java/net/causw/adapter/persistence/UserRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserAuthPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/BoardDetailDto.java
  src/main/java/net/causw/application/dto/CircleDto.java
  src/main/java/net/causw/application/dto/PostDetailDto.java
  src/main/java/net/causw/application/dto/UserAuthDto.java
  src/main/java/net/causw/application/dto/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/UserDetailDto.java
  src/main/java/net/causw/application/dto/UserFullDto.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
Labels: develop, enhancement

#55 feat: Locker Entity 추가
  src/main/java/net/causw/adapter/persistence/Locker.java
  src/main/java/net/causw/adapter/persistence/LockerRepository.java
  src/main/java/net/causw/adapter/persistence/User.java
  src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerDetailDto.java
  src/main/java/net/causw/application/spi/LockerPort.java
  src/main/java/net/causw/domain/model/LockerDomainModel.java
Labels: develop, enhancement

#44 feat: impl user api - email duplicate check and find by name
  src/main/java/net/causw/adapter/persistence/UserRepository.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/EmailDuplicatedCheckDto.java
  src/main/java/net/causw/application/spi/UserPort.java
Labels: develop, enhancement

#56 docs: CONTRIBUTE 가이드 수정
  CONTRIBUTE.md
  CONTRIBUTING.md
Labels: develop, documentation

#57 fix: Throw exception about invalid password and admission year
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
Labels: develop, enhancement

#60 fix: Specify nullable and default value in table column
  src/main/java/net/causw/adapter/persistence/Board.java
  src/main/java/net/causw/adapter/persistence/Circle.java
  src/main/java/net/causw/adapter/persistence/Locker.java
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/User.java
  src/main/java/net/causw/adapter/persistence/UserAuth.java
Labels: develop

#59 feat: spock test
  build.gradle
  docker-compose.yaml
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/UserAuthService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserCreateRequestDto.java
  src/main/resources/application-test.yaml
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, enhancement

#58 feat: LockerLog entity 정의 및 사물함 log api 구현
  src/main/java/net/causw/adapter/persistence/LockerLog.java
  src/main/java/net/causw/adapter/persistence/LockerLogRepository.java
  src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerLogDetailDto.java
  src/main/java/net/causw/application/spi/LockerLogPort.java
  src/main/java/net/causw/domain/model/LockerLogAction.java
Labels: develop, enhancement
