Repository CAUCSE/CAUSW_backend, pull requests merged in 2021-11, with the labels that each got.

#174 feat: locker location create, update implementation
  src/main/java/net/causw/adapter/persistence/LockerLocation.java
  src/main/java/net/causw/adapter/persistence/LockerLocationRepository.java
  src/main/java/net/causw/adapter/persistence/LockerRepository.java
  src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerLocationCreateRequestDto.java
  src/main/java/net/causw/application/dto/LockerLocationResponseDto.java
  src/main/java/net/causw/application/dto/LockerLocationUpdateRequestDto.java
  src/main/java/net/causw/application/spi/LockerLocationPort.java
  src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
Labels: enhancement, develop

#175 feat: Implement delete circle
  src/main/java/net/causw/adapter/persistence/Circle.java
  src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/CircleAllResponseDto.java
  src/main/java/net/causw/application/dto/CircleResponseDto.java
  src/main/java/net/causw/application/spi/CirclePort.java
  src/main/java/net/causw/domain/model/CircleDomainModel.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: enhancement, develop

#182 feat: post delete
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
Labels: enhancement, develop

#183 feat: post update
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/dto/PostUpdateRequestDto.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
  src/main/java/net/causw/domain/validation/UserRoleValidator.java
Labels: enhancement, develop

#186 feat: impl user admissions - create, findById, findAll
  src/main/java/net/causw/adapter/persistence/UserAdmission.java
  src/main/java/net/causw/adapter/persistence/UserAdmissionRepository.java
  src/main/java/net/causw/adapter/persistence/UserAuth.java
  src/main/java/net/causw/adapter/persistence/UserAuthRepository.java
  src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserAuthPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserAuthService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserAdmissionAllResponseDto.java
  src/main/java/net/causw/application/dto/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/application/dto/UserAdmissionResponseDto.java
  src/main/java/net/causw/application/dto/UserAuthDto.java
  src/main/java/net/causw/application/spi/UserAdmissionPort.java
  src/main/java/net/causw/application/spi/UserAuthPort.java
  src/main/java/net/causw/config/WebSecurityConfig.java
  src/main/java/net/causw/domain/model/UserAdmissionDomainModel.java
  src/main/java/net/causw/domain/model/UserState.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
  src/test/groovy/net/causw/application/BoardServiceTest.groovy
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop, refactor

#197 feat: impl home page & favorite board
  src/main/java/net/causw/adapter/persistence/FavoriteBoard.java
  src/main/java/net/causw/adapter/persistence/FavoriteBoardRepository.java
  src/main/java/net/causw/adapter/persistence/PageableFactory.java
  src/main/java/net/causw/adapter/persistence/port/FavoriteBoardPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/HomePageController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/HomePageService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/HomePageResponseDto.java
  src/main/java/net/causw/application/spi/FavoriteBoardPort.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/main/java/net/causw/config/WebSecurityConfig.java
  src/main/java/net/causw/domain/model/FavoriteBoardDomainModel.java
Labels: enhancement, develop

#198 Refactor post & comment response
  src/main/java/net/causw/adapter/web/CommentController.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/dto/CommentResponseDto.java
  src/main/java/net/causw/application/dto/PostResponseDto.java
  src/main/java/net/causw/domain/model/CircleDomainModel.java
Labels: develop, refactor

#201 feat: impl post update test case
  src/test/groovy/net/causw/application/PostServiceTest.groovy
Labels: enhancement, develop

#204 refac: Refactor entity to domain model mapper
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/FavoriteBoardPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
Labels: develop, refactor

#200 feat: 사물함 신규생성, 수정, 위치이동 api 구현
  src/main/java/net/causw/adapter/persistence/Locker.java
  src/main/java/net/causw/adapter/persistence/LockerLog.java
  src/main/java/net/causw/adapter/persistence/LockerRepository.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerCreateRequestDto.java
  src/main/java/net/causw/application/dto/LockerMoveRequestDto.java
  src/main/java/net/causw/application/dto/LockerResponseDto.java
  src/main/java/net/causw/application/dto/LockerUpdateRequestDto.java
  src/main/java/net/causw/application/spi/LockerLogPort.java
  src/main/java/net/causw/application/spi/LockerPort.java
  src/main/java/net/causw/domain/model/LockerDomainModel.java
Labels: enhancement, develop

#185 feat: add comment update #139
  src/main/java/net/causw/adapter/persistence/Comment.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/adapter/web/CommentController.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/dto/CommentUpdateRequestDto.java
  src/main/java/net/causw/application/spi/CommentPort.java
  src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
Labels: enhancement, develop

#184 feat: comment delete #140
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/adapter/web/CommentController.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/spi/CommentPort.java
Labels: enhancement, develop

#205 Implement accept & reject admission
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserAdmissionResponseDto.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#203 feat: Implement drop user
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/validation/UserRoleWithoutAdminValidator.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#206 feat: impl post delete test case
  src/test/groovy/net/causw/application/PostServiceTest.groovy
Labels: develop

#207 feat: impl comment update & delete test case
  src/main/java/net/causw/application/CommentService.java
  src/test/groovy/net/causw/application/CommentServiceTest.groovy
Labels: develop

#210 feat: locker, lockerLocation delete impl
  src/main/java/net/causw/adapter/persistence/LockerRepository.java
  src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/spi/LockerLocationPort.java
  src/main/java/net/causw/application/spi/LockerPort.java
Labels: enhancement, develop

#218 refac: Refactor error message
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/DelegationFactory.java
  src/main/java/net/causw/application/DelegationLeaderAlumni.java
  src/main/java/net/causw/application/DelegationLeaderCircle.java
  src/main/java/net/causw/application/DelegationPresident.java
  src/main/java/net/causw/application/HomePageService.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/model/BoardDomainModel.java
  src/main/java/net/causw/domain/model/CircleDomainModel.java
  src/main/java/net/causw/domain/model/CommentDomainModel.java
  src/main/java/net/causw/domain/model/FavoriteBoardDomainModel.java
  src/main/java/net/causw/domain/model/LockerDomainModel.java
  src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
  src/main/java/net/causw/domain/model/PostDomainModel.java
  src/main/java/net/causw/domain/model/UserAdmissionDomainModel.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
  src/main/java/net/causw/domain/validation/AdmissionYearValidator.java
  src/main/java/net/causw/domain/validation/CircleMemberStatusValidator.java
  src/main/java/net/causw/domain/validation/ContentsAdminValidator.java
  src/main/java/net/causw/domain/validation/GrantableRoleValidator.java
  src/main/java/net/causw/domain/validation/PasswordCorrectValidator.java
  src/main/java/net/causw/domain/validation/PasswordFormatValidator.java
  src/main/java/net/causw/domain/validation/StudentIdIsNullValidator.java
  src/main/java/net/causw/domain/validation/TargetIsDeletedValidator.java
  src/main/java/net/causw/domain/validation/TimePassedValidator.java
  src/main/java/net/causw/domain/validation/UserEqualValidator.java
  src/main/java/net/causw/domain/validation/UserNotEqualValidator.java
  src/main/java/net/causw/domain/validation/UserRoleValidator.java
  src/main/java/net/causw/domain/validation/UserRoleWithoutAdminValidator.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
Labels: develop, refactor

#219 refac: refactor locker update factory pattern with supplier
  src/main/java/net/causw/application/LockerAction.java
  src/main/java/net/causw/application/LockerActionDisable.java
  src/main/java/net/causw/application/LockerActionEnable.java
  src/main/java/net/causw/application/LockerActionFactory.java
  src/main/java/net/causw/application/LockerActionRegister.java
  src/main/java/net/causw/application/LockerActionReturn.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/config/LockerActionConfig.java
Labels: develop, refactor

#223 refac: Refactor target is deleted validator in post & comment
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/PostService.java
  src/test/groovy/net/causw/application/CommentServiceTest.groovy
  src/test/groovy/net/causw/application/PostServiceTest.groovy
Labels: develop, refactor

#191 feat: Connect to GCS
  build.gradle
  src/main/java/net/causw/adapter/persistence/User.java
  src/main/java/net/causw/adapter/web/StorageController.java
  src/main/java/net/causw/application/StorageService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UploadImageResponseDto.java
  src/main/java/net/causw/application/dto/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/UserUpdateRequestDto.java
  src/main/java/net/causw/domain/model/ImageLocation.java
  src/main/resources/application-local.yaml
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop, devops

#224 refac: Refactor sign in
  src/main/java/net/causw/adapter/persistence/UserAdmissionRepository.java
  src/main/java/net/causw/adapter/persistence/port/UserAdmissionPortImpl.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/UserAdmissionPort.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
Labels: develop, refactor

#225 refac: locker action factory bean함수 말고 component 처리
  src/main/java/net/causw/application/LockerActionFactory.java
  src/main/java/net/causw/config/LockerActionConfig.java
Labels: enhancement, develop

#226 fix: LockerDomainModel location 필수처리
  src/main/java/net/causw/domain/model/LockerDomainModel.java
Labels: enhancement, develop

#220 feat: impl auto create favorite board
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
Labels: enhancement, develop

#230 fix: modify response for post and comment
  src/main/java/net/causw/adapter/persistence/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/dto/PostAllResponseDto.java
  src/main/java/net/causw/application/dto/PostResponseDto.java
Labels: develop, refactor

#231 fix: solve cors issue
  src/main/java/net/causw/config/WebSecurityConfig.java
Labels: develop, devops

#232 fix: modify comment response
  src/main/java/net/causw/application/dto/CommentResponseDto.java
Labels: develop, refactor

#240 fix: allow cors for all origin
  src/main/java/net/causw/config/WebSecurityConfig.java
Labels: develop, refactor
