Repository CAUCSE/CAUSW_backend, pull requests merged in 2021-12, with the labels that each got.

#245 fix: typo in comment controller
  src/main/java/net/causw/adapter/web/CommentController.java
Labels: bug, develop

#246 fix: Fix bug about comment
  src/main/java/net/causw/adapter/persistence/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/application/dto/CommentResponseDto.java
Labels: bug, develop

#243 feat: Add app notice board
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/main/resources/application-local.yaml
Labels: enhancement, develop

#247 test: lockerService TC 구현
  src/main/java/net/causw/domain/model/LockerDomainModel.java
  src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: develop, Need TC

#241 refac: Add validation about user role and state
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/HomePageService.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/config/JwtAuthenticationEntryPoint.java
  src/main/java/net/causw/config/JwtTokenProvider.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/UserState.java
  src/main/java/net/causw/domain/validation/UserRoleIsNoneValidator.java
Labels: develop, refactor

#255 refac: LockerService update 메소드 내부 수정
  src/main/java/net/causw/application/LockerActionDisable.java
  src/main/java/net/causw/application/LockerActionEnable.java
  src/main/java/net/causw/application/LockerActionRegister.java
  src/main/java/net/causw/application/LockerActionReturn.java
  src/main/java/net/causw/application/LockerService.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: develop, refactor
