Repository CAUCSE/CAUSW_backend, pull requests merged in 2021-09, with the labels that each got.

#93 feat: accept & reject user of circle
  src/main/java/net/causw/adapter/persistence/UserCircle.java
  src/main/java/net/causw/adapter/persistence/port/UserCirclePortImpl.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/spi/UserCirclePort.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/CircleDomainModel.java
  src/main/java/net/causw/domain/model/UserCircleStatus.java
  src/main/java/net/causw/domain/validation/UserCircleStateAwaitValidator.java
  src/main/java/net/causw/domain/validation/UserEqualValidator.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: enhancement, develop

#95 refac: Refactor validation model
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/validation/AbstractValidator.java
  src/main/java/net/causw/domain/validation/AdmissionYearValidator.java
  src/main/java/net/causw/domain/validation/BoardRoleValidator.java
  src/main/java/net/causw/domain/validation/CircleStateValidator.java
  src/main/java/net/causw/domain/validation/ConstraintValidator.java
  src/main/java/net/causw/domain/validation/CorrectCircleLeaderValidator.java
  src/main/java/net/causw/domain/validation/DuplicatedCircleNameValidator.java
  src/main/java/net/causw/domain/validation/DuplicatedEmailValidator.java
  src/main/java/net/causw/domain/validation/PasswordCorrectValidator.java
  src/main/java/net/causw/domain/validation/PasswordFormatValidator.java
  src/main/java/net/causw/domain/validation/UpdatableGrantedRoleValidator.java
  src/main/java/net/causw/domain/validation/UpdatableGranteeRoleValidator.java
  src/main/java/net/causw/domain/validation/UserCircleStateAwaitValidator.java
  src/main/java/net/causw/domain/validation/UserCircleStateLeaveValidator.java
  src/main/java/net/causw/domain/validation/UserCircleStateValidator.java
  src/main/java/net/causw/domain/validation/UserEqualValidator.java
  src/main/java/net/causw/domain/validation/UserRoleAdminOrPresidentValidator.java
  src/main/java/net/causw/domain/validation/UserRoleValidator.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
  src/main/java/net/causw/domain/validation/ValidatorBucket.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: bug, develop

#102 feat: Implement to update user password
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserPasswordUpdateRequestDto.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#101 feat: Implement to delete board
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/dto/BoardUpdateRequestDto.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/main/java/net/causw/domain/model/BoardDomainModel.java
  src/test/groovy/net/causw/application/BoardServiceTest.groovy
Labels: enhancement, develop

#107 feat: Implement to update circle
  src/main/java/net/causw/adapter/persistence/port/CirclePortImpl.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/dto/CircleUpdateRequestDto.java
  src/main/java/net/causw/application/spi/CirclePort.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: enhancement, develop

#105 feat: Implement to leave user
  src/main/java/net/causw/adapter/persistence/CircleMemberRepository.java
  src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/CircleMemberPort.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#118 feat: Implement to get circle to which the user has joined
  src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/CircleMemberPort.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#117 feat: Implement board find by circle id
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/main/java/net/causw/domain/validation/CircleMemberInvalidStatusValidator.java
  src/test/groovy/net/causw/application/BoardServiceTest.groovy
Labels: enhancement, develop

#119 feat: Implement to get user list in circle
  src/main/java/net/causw/adapter/persistence/CircleMemberRepository.java
  src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/spi/CircleMemberPort.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: enhancement, develop

#121 refac: Delete validator which uses port
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/validation/DuplicatedCircleNameValidator.java
  src/main/java/net/causw/domain/validation/DuplicatedEmailValidator.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop
