Repository CAUCSE/CAUSW_backend, pull requests merged in 2022-02, with the labels that each got.

#268 feat: Implement search post
  src/main/java/net/causw/adapter/persistence/PostRepository.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/main/java/net/causw/domain/model/SearchOption.java
  src/test/groovy/net/causw/application/PostServiceTest.groovy
Labels: enhancement, develop

#269 feat: Implement find my posts
  src/main/java/net/causw/adapter/persistence/PostRepository.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/PostAllForUserResponseDto.java
  src/main/java/net/causw/application/dto/UserPostResponseDto.java
  src/main/java/net/causw/application/spi/PostPort.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#270 feat: Implement find my comments
  src/main/java/net/causw/adapter/persistence/Comment.java
  src/main/java/net/causw/adapter/persistence/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/CommentAllForUserResponseDto.java
  src/main/java/net/causw/application/dto/CommentResponseDto.java
  src/main/java/net/causw/application/dto/UserCommentResponseDto.java
  src/main/java/net/causw/application/spi/CommentPort.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#272 refac: Refactor find boards of circle
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/dto/CircleWithBoardsResponseDto.java
  src/test/groovy/net/causw/application/BoardServiceTest.groovy
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: develop, refactor

#273 refac: Refactor board of circle response dto
  src/main/java/net/causw/application/dto/BoardOfCircleResponseDto.java
Labels: develop, refactor

#267 feat: Add email service skel
  build.gradle
  src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/config/JwtTokenProvider.java
  src/main/java/net/causw/config/MailProperties.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/exceptions/ServiceUnavailableException.java
  src/main/java/net/causw/domain/model/ImageLocation.java
  src/main/java/net/causw/infrastructure/GoogleMailSender.java
  src/main/resources/application-local.yaml
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#274 fix: refactor circle join status in circle all response dto
  src/main/java/net/causw/adapter/persistence/port/CircleMemberPortImpl.java
Labels: develop, refactor

#275 fix: refactor findCurrentUser to include circle info if leader
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserResponseDto.java
  src/main/resources/application-local.yaml
Labels: develop, refactor

#276 fix: internal server error on get post caused by comment sort
  src/main/java/net/causw/adapter/persistence/port/ChildCommentPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
Labels: bug, develop, refactor

#279 fix: refactor content in CommentResponseDto for deleted case
  src/main/java/net/causw/application/dto/ChildCommentResponseDto.java
  src/main/java/net/causw/application/dto/CommentResponseDto.java
  src/main/java/net/causw/domain/model/StaticValue.java
Labels: develop, refactor

#280 fix: refactor optional variable in dto
  src/main/java/net/causw/application/dto/ChildCommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/ChildCommentUpdateRequestDto.java
Labels: bug, develop, refactor

#281 fix: refactor child commnent order to ASC
  src/main/java/net/causw/adapter/persistence/ChildCommentRepository.java
  src/main/java/net/causw/adapter/persistence/port/ChildCommentPortImpl.java
Labels: develop, refactor

#283 fix: refactor ChildCommentDto to include parent comment information
  src/main/java/net/causw/adapter/web/ChildCommentController.java
  src/main/java/net/causw/application/ChildCommentService.java
  src/main/java/net/causw/application/dto/ChildCommentAllResponseDto.java
Labels: develop, refactor

#292 refac: Refactor ref comment and tag user of child comment
  src/main/java/net/causw/application/ChildCommentService.java
  src/main/java/net/causw/application/dto/ChildCommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/ChildCommentUpdateRequestDto.java
  src/main/java/net/causw/domain/model/ChildCommentDomainModel.java
  src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#294 fix: Fix find posts and comments of user
  src/main/java/net/causw/adapter/persistence/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/PostRepository.java
  src/main/java/net/causw/adapter/persistence/port/CommentPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/application/UserService.java
Labels: bug, develop

#297 refac: Refactor type of attachImage in user apply string to multipartfile
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/StorageService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/infrastructure/GcpFileUploader.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#299 fix: Fix query about find posts and comments of user
  src/main/java/net/causw/adapter/persistence/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/PostRepository.java
Labels: bug, develop

#300 refac: Refactor generate random password
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/CommentAllForUserResponseDto.java
  src/main/java/net/causw/application/dto/PostAllForUserResponseDto.java
  src/main/java/net/causw/domain/model/UserDomainModel.java
  src/main/java/net/causw/infrastructure/PasswordGenerator.java
  src/main/resources/application-local.yaml
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#303 fix: refactor locker findAllLocations to include my locker information
  src/main/java/net/causw/adapter/persistence/LockerRepository.java
  src/main/java/net/causw/adapter/persistence/port/LockerPortImpl.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerActionEnable.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerAllLocationResponseDto.java
  src/main/java/net/causw/application/spi/LockerPort.java
Labels: develop, refactor

#304 fix: refactor LockerResponseDto to include isMine field
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerResponseDto.java
Labels: develop, refactor

#307 fix: refactor LockerResponseDto to include location name
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerAllResponseDto.java
  src/main/java/net/causw/application/dto/LockerResponseDto.java
Labels: develop, refactor

#309 fix: fix register locker
  src/main/java/net/causw/adapter/persistence/LockerLogRepository.java
  src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
  src/main/java/net/causw/application/LockerAction.java
  src/main/java/net/causw/application/LockerActionDisable.java
  src/main/java/net/causw/application/LockerActionEnable.java
  src/main/java/net/causw/application/LockerActionRegister.java
  src/main/java/net/causw/application/LockerActionReturn.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerLogDetailDto.java
  src/main/java/net/causw/application/spi/LockerLogPort.java
  src/main/java/net/causw/domain/model/LockerDomainModel.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: bug, develop, refactor

#313 feat: user findById for searching another user case
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
Labels: enhancement, develop

#312 fix: refactor Locker Structure to remove unnecessary field
  src/main/java/net/causw/adapter/persistence/LockerLocation.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/LockerLocationPortImpl.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/LockerLocationCreateRequestDto.java
  src/main/java/net/causw/application/dto/LockerLocationResponseDto.java
  src/main/java/net/causw/application/dto/LockerLocationUpdateRequestDto.java
  src/main/java/net/causw/application/dto/LockerLogDetailDto.java
  src/main/java/net/causw/application/dto/LockerMoveRequestDto.java
  src/main/java/net/causw/application/dto/LockerUpdateRequestDto.java
  src/main/java/net/causw/domain/model/LockerLocationDomainModel.java
Labels: develop, refactor

#314 refac: Add President user give Leader Circle role
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserUpdateRoleRequestDto.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#320 refac: Refactor find by name for leader circle
  src/main/java/net/causw/application/UserService.java
Labels: develop, refactor

#323 refac: Refactor find all user admission dto
  src/main/java/net/causw/application/dto/UserAdmissionAllResponseDto.java
Labels: develop, refactor

#325 refac: Return locker in leave and drop user
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserAdmissionAllResponseDto.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#321 feat: Implement find email
  src/main/java/net/causw/adapter/persistence/UserRepository.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/UserFindEmailRequestDto.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/main/java/net/causw/config/WebSecurityConfig.java
Labels: enhancement, develop
