Repository CAUCSE/CAUSW_backend, pull requests merged in 2022-08, with the labels that each got.

#421 refac: refactor extend locker validator
  src/main/java/net/causw/application/LockerActionExtend.java
Labels: refactor

#422 refac: refactor locker dto
  src/main/java/net/causw/application/dto/locker/LockerResponseDto.java
Labels: refactor

#423 fix: fix bug about locker domain model
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/domain/model/LockerDomainModel.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: bug

#417 feat: Implement Inquiry
  src/main/java/net/causw/adapter/persistence/Inquiry.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/InquiryPortImpl.java
  src/main/java/net/causw/adapter/persistence/port/InquiryRepository.java
  src/main/java/net/causw/adapter/web/InquiryController.java
  src/main/java/net/causw/application/InquiryService.java
  src/main/java/net/causw/application/dto/inquiry/InquiryCreateRequestDto.java
  src/main/java/net/causw/application/dto/inquiry/InquiryResponseDto.java
  src/main/java/net/causw/application/spi/InquiryPort.java
  src/main/java/net/causw/domain/model/InquiryDomainModel.java
  src/main/java/net/causw/domain/model/StaticValue.java
Labels: enhancement, develop
