Repository CAUCSE/CAUSW_backend, pull requests merged in 2022-03, with the labels that each got.

#326 fix: Fix user state bug in find by name
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/model/UserAdmissionDomainModel.java
Labels: develop, refactor

#329 fix: remove exception process for admin account (TODO)
  src/main/java/net/causw/domain/model/UserDomainModel.java
Labels: develop

#330 fix: remove deployment script
  .gitignore
  deploy_backend.sh
Labels: develop

#333 fix: update deploy profile for app engine
  .gitignore
  src/main/appengine/app.yaml
Labels: develop, devops

#328 fix: add handling for inactive & drop user rejoin
  src/main/java/net/causw/application/UserService.java
Labels: develop, refactor

#334 fix: bug at removing circle
  src/main/java/net/causw/adapter/persistence/Circle.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
Labels: bug, develop, refactor

#335 fix: bug at granting leader alumni
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/domain/validation/GrantableRoleValidator.java
Labels: bug, develop, refactor

#338 feat: Add test to CI
  .github/workflows/ci.yml
  build.gradle
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, devops

#331 fix: update README
  .github/workflows/ci.yml
  .gitignore
  docker-compose.yaml
  img/project_structure.png
  readme.md
Labels: documentation, develop

#339 fix: readme
  img/project_structure.png
  readme.md
Labels: documentation, develop

#340 fix: Update isActive when register and return locker
  src/main/java/net/causw/domain/model/LockerDomainModel.java
Labels: develop, refactor

#341 fix: exception for first sign-in
  src/main/java/net/causw/application/UserService.java
Labels: bug, develop

#342 fix: exception in creating favorite board
  src/main/java/net/causw/application/UserService.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: bug, develop

#343 fix: add exception handling for reject user sign-in
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
Labels: bug, develop

#346 fix: modify lombok annotation for request dto
  src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
  src/main/java/net/causw/application/dto/board/BoardUpdateRequestDto.java
  src/main/java/net/causw/application/dto/circle/CircleCreateRequestDto.java
  src/main/java/net/causw/application/dto/circle/CircleUpdateRequestDto.java
  src/main/java/net/causw/application/dto/comment/ChildCommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/comment/ChildCommentUpdateRequestDto.java
  src/main/java/net/causw/application/dto/comment/CommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/comment/CommentUpdateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerLocationCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerLocationUpdateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerMoveRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerUpdateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserFindEmailRequestDto.java
  src/main/java/net/causw/application/dto/user/UserSignInRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdatePasswordRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java
Labels: develop, refactor

#347 fix: update README to include app url
  readme.md
Labels: documentation, develop

#349 fix: change image field of circle into nullable
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/domain/model/CircleDomainModel.java
Labels: develop, refactor

#350 fix: update README
  .gitignore
  readme.md
  src/main/appengine/app.yaml
Labels: documentation, develop

#351 refac: Refactor dto get user list of circle
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/dto/circle/CircleMemberResponseDto.java
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: develop, refactor

#352 refac: Refactor home page
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/CommonController.java
  src/main/java/net/causw/application/HomePageService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/BoardPort.java
Labels: develop, refactor

#353 refac: Refactor to register locker
  src/main/java/net/causw/application/LockerService.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: develop, refactor

#354 fix: Fix get user list of circle
  src/main/java/net/causw/application/CircleService.java
Labels: bug, develop

#355 fix: Fix GCS file path
  src/main/java/net/causw/infrastructure/GcpFileUploader.java
Labels: bug, develop

#358 fix: Fix bug of gcs image upload
  src/main/java/net/causw/infrastructure/GcpFileUploader.java
Labels: bug, develop

#357 feat: Attach file
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/PostPortImpl.java
  src/main/java/net/causw/adapter/web/StorageController.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/StorageService.java
  src/main/java/net/causw/application/dto/FileResponseDto.java
  src/main/java/net/causw/application/dto/UploadFileResponseDto.java
  src/main/java/net/causw/application/dto/UploadImageResponseDto.java
  src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
  src/main/java/net/causw/domain/model/PostDomainModel.java
  src/main/java/net/causw/domain/model/StaticValue.java
  src/main/java/net/causw/domain/validation/AttachmentSizeValidator.java
  src/main/java/net/causw/domain/validation/ImageSizeValidator.java
  src/main/java/net/causw/domain/validation/PostNumberOfAttachmentsValidator.java
  src/main/java/net/causw/infrastructure/GcpFileUploader.java
  src/main/resources/application-local.yaml
  src/test/groovy/net/causw/application/ChildCommentServiceTest.groovy
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
  src/test/groovy/net/causw/application/CommentServiceTest.groovy
  src/test/groovy/net/causw/application/PostServiceTest.groovy
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: enhancement, develop

#364 fix: update variable for attach file
  src/main/java/net/causw/application/dto/FileResponseDto.java
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/domain/model/StaticValue.java
  src/main/java/net/causw/domain/validation/PostNumberOfAttachmentsValidator.java
Labels: develop, refactor

#369 refac: Change max length of image and attachment url
  src/main/java/net/causw/adapter/persistence/Circle.java
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/User.java
  src/main/java/net/causw/adapter/persistence/UserAdmission.java
  src/main/java/net/causw/adapter/persistence/UserAdmissionLog.java
Labels: develop, refactor

#363 refac: Allow admin related circle
  src/main/java/net/causw/application/ChildCommentService.java
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/CommentService.java
  src/main/java/net/causw/application/PostService.java
Labels: develop, refactor

#365 fix: favorite board initialize
  src/main/java/net/causw/adapter/persistence/BoardRepository.java
  src/main/java/net/causw/adapter/persistence/port/BoardPortImpl.java
  src/main/java/net/causw/adapter/web/CommonController.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/HomePageService.java
  src/main/java/net/causw/application/PostService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/post/BoardPostsResponseDto.java
  src/main/java/net/causw/application/spi/BoardPort.java
  src/test/groovy/net/causw/application/PostServiceTest.groovy
Labels: develop, refactor

#368 refac: Add password encoder
  src/main/java/net/causw/adapter/persistence/UserRepository.java
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/main/java/net/causw/config/WebSecurityConfig.java
  src/main/java/net/causw/config/WebSecurityConfigProd.java
  src/main/java/net/causw/domain/validation/PasswordCorrectValidator.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#374 fix: remove password all encoder
  src/main/java/net/causw/adapter/persistence/port/UserPortImpl.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/UserPort.java
Labels: develop, refactor

#372 fix: Fix null pointer exception of post attachments
  src/main/java/net/causw/adapter/persistence/Post.java
  src/main/java/net/causw/adapter/persistence/port/DomainModelMapper.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
Labels: bug, develop

#379 chore: update WebSecurityConfig
  src/main/java/net/causw/config/WebSecurityConfig.java
  src/main/java/net/causw/config/WebSecurityConfigProd.java
Labels: develop, devops

#378 fix: modify check logic for locker register
  src/main/java/net/causw/adapter/persistence/Flag.java
  src/main/java/net/causw/adapter/persistence/FlagRepository.java
  src/main/java/net/causw/adapter/persistence/port/FlagPortImpl.java
  src/main/java/net/causw/adapter/web/CommonController.java
  src/main/java/net/causw/application/CommonService.java
  src/main/java/net/causw/application/LockerAction.java
  src/main/java/net/causw/application/LockerActionDisable.java
  src/main/java/net/causw/application/LockerActionEnable.java
  src/main/java/net/causw/application/LockerActionRegister.java
  src/main/java/net/causw/application/LockerActionReturn.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/spi/FlagPort.java
  src/main/java/net/causw/domain/model/StaticValue.java
  src/main/java/net/causw/domain/validation/LockerAccessValidator.java
  src/main/java/net/causw/domain/validation/LockerInUseValidator.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: develop, refactor

#382 fix: Fix bug of user admission in sign-in
  src/main/java/net/causw/application/UserService.java
Labels: bug, develop

#381 fix: Get circle list for admin
  src/main/java/net/causw/application/CircleService.java
  src/main/java/net/causw/application/dto/circle/CirclesResponseDto.java
Labels: develop, refactor

#384 fix: Fix bug of find all location for admin
  src/main/java/net/causw/application/LockerService.java
Labels: bug, develop

#385 fix: remove locker time pass check logic for admin
  src/main/java/net/causw/application/LockerActionRegister.java
Labels: develop, refactor

#390 fix: Add locker location name in locker location table
  src/main/java/net/causw/adapter/persistence/LockerLog.java
  src/main/java/net/causw/adapter/persistence/port/LockerLogPortImpl.java
  src/main/java/net/causw/application/LockerActionRegister.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/UserService.java
  src/main/java/net/causw/application/spi/LockerLogPort.java
Labels: develop, refactor

#386 fix: modify locker response for duplicate locker number
  src/main/java/net/causw/adapter/persistence/Locker.java
  src/main/java/net/causw/application/LockerService.java
  src/main/java/net/causw/application/dto/locker/LockerResponseDto.java
  src/test/groovy/net/causw/application/LockerServiceTest.groovy
Labels: develop, refactor

#392 refac: Refactor user service and test code
  src/main/java/net/causw/application/UserService.java
  src/test/groovy/net/causw/application/UserServiceTest.groovy
Labels: develop, refactor

#395 refac: Refactor circle and board service and test code
  src/main/java/net/causw/application/BoardService.java
  src/main/java/net/causw/application/CircleService.java
  src/test/groovy/net/causw/application/BoardServiceTest.groovy
  src/test/groovy/net/causw/application/CircleServiceTest.groovy
Labels: develop, refactor
