Repository CAUCSE/CAUSW_backend, pull requests merged in 2024-09, with the labels that each got.

#612 feat : locker 연장 구현
  src/main/java/net/causw/application/locker/LockerActionExtend.java
  src/main/java/net/causw/application/locker/LockerActionRegister.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
  src/main/java/net/causw/domain/model/util/StaticValue.java
  src/main/java/net/causw/domain/validation/ExtendLockerExpiredAtValidator.java
  src/main/java/net/causw/domain/validation/LockerExpiredAtValidator.java
  src/main/java/net/causw/domain/validation/LockerExtendAccessValidator.java
  src/main/java/net/causw/domain/validation/LockerInUseValidator.java
Labels: feat

#611 feature : 탈퇴 회원 계정 삭제
  src/main/java/net/causw/CauswApplication.java
  src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/application/comment/ChildCommentService.java
  src/main/java/net/causw/application/comment/CommentService.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/enums/UserState.java
  src/main/java/net/causw/domain/validation/UserStateIsDeletedValidator.java
  src/main/java/net/causw/domain/validation/UserStateIsDropOrIsInActiveValidator.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
Labels: enhancement

#602 refactor: 임시 비밀번호 발급 및 메일 전송
  src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
  src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
  src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
  src/main/java/net/causw/application/spi/UserPort.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/config/mail/MailConfig.java
  src/main/java/net/causw/infrastructure/GoogleMailSender.java
Labels: refactor

#600 refactor: UserService에 DtoMapper 적용
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/application/user/UserService.java
Labels: refactor

#617 Devops: workflow 빌드 에러 해결
  .github/workflows/dev.yml
  .github/workflows/main.yml
Labels: devops

#608 refactor: 유저기록을 위한 API 추가
  src/main/java/net/causw/adapter/persistence/repository/ChildCommentRepository.java
  src/main/java/net/causw/adapter/persistence/repository/CommentRepository.java
  src/main/java/net/causw/adapter/persistence/repository/FavoritePostRepository.java
  src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
  src/main/java/net/causw/adapter/web/ChildCommentController.java
  src/main/java/net/causw/adapter/web/CommentController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/dto/post/PostsResponseDto.java
  src/main/java/net/causw/application/dto/user/UserPostsResponseDto.java
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/application/user/UserService.java
Labels: refactor

#610 refactor : 개인정보 관리 페이지 리팩토링
  src/main/java/net/causw/adapter/persistence/port/mapper/DomainModelMapper.java
  src/main/java/net/causw/adapter/persistence/port/user/UserPortImpl.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/dto/comment/ChildCommentResponseDto.java
  src/main/java/net/causw/application/dto/comment/CommentResponseDto.java
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/application/dto/user/UserCommentsResponseDto.java
  src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserPostsResponseDto.java
  src/main/java/net/causw/application/dto/user/UserResponseDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/domain/model/user/UserDomainModel.java
Labels: refactor

#618 refactor : 일반 게시판 생성 / 신청 API
  src/main/java/net/causw/adapter/persistence/board/Board.java
  src/main/java/net/causw/adapter/persistence/board/BoardApply.java
  src/main/java/net/causw/adapter/persistence/repository/BoardApplyRepository.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/board/NormalBoardApplyRequestDto.java
  src/main/java/net/causw/application/dto/board/NormalBoardCreateRequestDto.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/util/StaticValue.java
Labels: refactor

#621 feature : 홈 화면 관리 관련 기능 개발
  src/main/java/net/causw/adapter/persistence/calendar/Calendar.java
  src/main/java/net/causw/adapter/persistence/event/Event.java
  src/main/java/net/causw/adapter/persistence/repository/CalendarRepository.java
  src/main/java/net/causw/adapter/persistence/repository/EventRepository.java
  src/main/java/net/causw/adapter/web/CalendarController.java
  src/main/java/net/causw/adapter/web/EventController.java
  src/main/java/net/causw/application/calendar/CalendarService.java
  src/main/java/net/causw/application/dto/calendar/CalendarCreateRequestDto.java
  src/main/java/net/causw/application/dto/calendar/CalendarResponseDto.java
  src/main/java/net/causw/application/dto/calendar/CalendarUpdateRequestDto.java
  src/main/java/net/causw/application/dto/calendar/CalendarsResponseDto.java
  src/main/java/net/causw/application/dto/event/EventCreateRequestDto.java
  src/main/java/net/causw/application/dto/event/EventResponseDto.java
  src/main/java/net/causw/application/dto/event/EventUpdateRequestDto.java
  src/main/java/net/causw/application/dto/event/EventsResponseDto.java
  src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/application/event/EventService.java
  src/main/java/net/causw/domain/model/enums/ImageLocation.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
  src/main/java/net/causw/domain/model/util/StaticValue.java
Labels: enhancement

#623 refactor : RequestDto에 Valid 적용
  src/main/java/net/causw/adapter/persistence/base/BaseEntity.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/adapter/web/ChildCommentController.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/adapter/web/CommentController.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/adapter/web/GlobalExceptionHandler.java
  src/main/java/net/causw/adapter/web/InquiryController.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
  src/main/java/net/causw/application/dto/board/BoardUpdateRequestDto.java
  src/main/java/net/causw/application/dto/circle/CircleCreateRequestDto.java
  src/main/java/net/causw/application/dto/circle/CircleUpdateRequestDto.java
  src/main/java/net/causw/application/dto/comment/ChildCommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/comment/ChildCommentUpdateRequestDto.java
  src/main/java/net/causw/application/dto/comment/CommentCreateRequestDto.java
  src/main/java/net/causw/application/dto/comment/CommentUpdateRequestDto.java
  src/main/java/net/causw/application/dto/form/FormCreateRequestDto.java
  src/main/java/net/causw/application/dto/form/OptionCreateRequestDto.java
  src/main/java/net/causw/application/dto/form/QuestionCreateRequestDto.java
  src/main/java/net/causw/application/dto/form/QuestionReplyRequestDto.java
  src/main/java/net/causw/application/dto/inquiry/InquiryCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerLocationCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerLocationUpdateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerMoveRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerUpdateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostCreateRequestDto.java
  src/main/java/net/causw/application/dto/post/PostUpdateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserAdmissionCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserFindPasswordRequestDto.java
  src/main/java/net/causw/application/dto/user/UserSignInRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdatePasswordRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRoleRequestDto.java
Labels: refactor

#625 feature: 게시판 관리 기능 구현
  src/main/java/net/causw/adapter/persistence/board/BoardApply.java
  src/main/java/net/causw/adapter/persistence/repository/BoardApplyRepository.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/dto/board/NormalBoardAppliesResponseDto.java
  src/main/java/net/causw/application/dto/board/NormalBoardApplyResponseDto.java
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/domain/model/enums/BoardApplyStatus.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: feat

#626 Feat: 학생회비 관리 기능 구현
  src/main/java/net/causw/adapter/persistence/calendar/Calendar.java
  src/main/java/net/causw/adapter/persistence/event/Event.java
  src/main/java/net/causw/adapter/persistence/repository/CouncilFeeFakeUserRepository.java
  src/main/java/net/causw/adapter/persistence/repository/UserAcademicRecordApplicationRepository.java
  src/main/java/net/causw/adapter/persistence/repository/UserAcademicRecordLogRepository.java
  src/main/java/net/causw/adapter/persistence/repository/UserCouncilFeeLogRepository.java
  src/main/java/net/causw/adapter/persistence/repository/UserCouncilFeeRepository.java
  src/main/java/net/causw/adapter/persistence/repository/UserRepository.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordApplication.java
  src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordLog.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/CouncilFeeFakeUser.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFee.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFeeLog.java
  src/main/java/net/causw/adapter/web/SemesterController.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/adapter/web/UserCouncilFeeController.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/userCouncilFee/CreateUserCouncilFeeRequestDto.java
  src/main/java/net/causw/application/dto/userCouncilFee/UserCouncilFeeListResponseDto.java
  src/main/java/net/causw/application/dto/userCouncilFee/UserCouncilFeeResponseDto.java
  src/main/java/net/causw/application/dto/util/UserAcademicRecordDtoMapper.java
  src/main/java/net/causw/application/dto/util/UserCouncilFeeDtoMapper.java
  src/main/java/net/causw/application/excel/CircleExcelService.java
  src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
  src/main/java/net/causw/application/excel/ExcelAbstractService.java
  src/main/java/net/causw/application/excel/ExcelService.java
  src/main/java/net/causw/application/semester/SemesterService.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
  src/main/java/net/causw/domain/model/enums/LogType.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: enhancement, refactor, feat

#641 refactor : 유저관리 페이지 리팩토링
  src/main/java/net/causw/adapter/persistence/port/user/UserAdmissionLogPortImpl.java
  src/main/java/net/causw/adapter/persistence/repository/UserAdmissionRepository.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/persistence/user/UserAdmissionLog.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/dto/user/UserAdmissionResponseDto.java
  src/main/java/net/causw/application/dto/user/UserAdmissionsResponseDto.java
  src/main/java/net/causw/application/dto/user/UserResponseDto.java
  src/main/java/net/causw/application/dto/util/DtoMapper.java
  src/main/java/net/causw/application/dto/util/dtoMapper/UserDtoMapper.java
  src/main/java/net/causw/application/spi/UserAdmissionLogPort.java
  src/main/java/net/causw/application/user/UserService.java
Labels: refactor

#643 refactor: 사용자가 게시글/댓글에 좋아요를 이미 누른지 여부를 확인하는 필드 추가
  .gitignore
  src/main/generated/net/causw/application/dto/util/dtoMapper/BoardDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/CalendarDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/CircleDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/CommentDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/EventDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/FormDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/PostDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/SemesterDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/UserAcademicRecordDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/UserCouncilFeeDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/UserDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/custom/FormatDateTimeDtoMapperImpl.java
  src/main/generated/net/causw/application/dto/util/dtoMapper/custom/UuidFileToUrlDtoMapperImpl.java
  src/main/java/net/causw/adapter/persistence/repository/PostRepository.java
  src/main/java/net/causw/application/comment/ChildCommentService.java
  src/main/java/net/causw/application/comment/CommentService.java
  src/main/java/net/causw/application/dto/comment/ChildCommentResponseDto.java
  src/main/java/net/causw/application/dto/comment/ChildCommentsResponseDto.java
  src/main/java/net/causw/application/dto/comment/CommentResponseDto.java
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/CommentDtoMapper.java
  src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/domain/validation/PostNumberOfAttachmentsValidator.java
Labels: refactor

#642 feat : 이미 가입한 학번인지 확인하는 api 추가
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/user/UserService.java
Labels: feat

#646 devops: Grafana 기반 모니터링 대시보드 구축 (#645)
  build.gradle
  src/main/java/net/causw/config/favicon/FaviconController.java
  src/main/java/net/causw/config/security/WebSecurityConfig.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback.xml
Labels: devops

#655 hotfix : 개인정보 수정 학번,전화번호 체크 로직 삭제
  src/main/java/net/causw/application/user/UserService.java
Labels: hotfix

#659 chore: AOP 기반 메서드별 이름/실행시간 로깅 #658
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/calendar/CalendarService.java
  src/main/java/net/causw/application/circle/CircleMemberService.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/comment/ChildCommentService.java
  src/main/java/net/causw/application/comment/CommentService.java
  src/main/java/net/causw/application/common/CommonService.java
  src/main/java/net/causw/application/crawler/WebCrawlerService.java
  src/main/java/net/causw/application/event/EventService.java
  src/main/java/net/causw/application/excel/CircleExcelService.java
  src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
  src/main/java/net/causw/application/form/FormService.java
  src/main/java/net/causw/application/homepage/HomePageService.java
  src/main/java/net/causw/application/inquiry/InquiryService.java
  src/main/java/net/causw/application/locker/LockerService.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/application/semester/SemesterService.java
  src/main/java/net/causw/application/storage/StorageManager.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
  src/main/java/net/causw/application/uuidFile/CleanUnusedUuidFileService.java
  src/main/java/net/causw/application/uuidFile/UuidFileService.java
  src/main/java/net/causw/domain/aop/LogAspect.java
  src/main/java/net/causw/domain/aop/annotation/MeasureTime.java
Labels: chore

#661 fix: Controller의 swagger 오타 수정 및 Entity Enum 클래스들 Enumrated String으로 수정
  src/main/java/net/causw/adapter/persistence/board/BoardApply.java
  src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordApplication.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFeeLog.java
  src/main/java/net/causw/adapter/web/UserCouncilFeeController.java
  src/main/java/net/causw/domain/model/enums/BoardApplyStatus.java
Labels: docs, chore

#662 feat: excel export 구현
  .gitignore
  build.gradle
  src/main/java/net/causw/adapter/persistence/repository/circle/CircleMemberRepository.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/circle/ExportCircleMemberToExcelResponseDto.java
  src/main/java/net/causw/application/dto/userAcademicRecordApplication/UserAcademicRecordApplicationResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java
  src/main/java/net/causw/application/dto/util/dtoMapper/custom/UuidFileToUrlDtoMapper.java
  src/main/java/net/causw/application/excel/CircleExcelService.java
  src/main/java/net/causw/application/excel/ExcelAbstractService.java
  src/main/java/net/causw/application/excel/ExcelService.java
  src/main/java/net/causw/application/excel/UserAcademicRecordExcelService.java
  src/main/java/net/causw/application/excel/UserExcelService.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
  src/main/java/net/causw/domain/model/enums/AcademicStatus.java
  src/main/java/net/causw/domain/model/enums/FilePath.java
  src/main/java/net/causw/domain/model/enums/GraduationType.java
  src/main/java/net/causw/domain/model/enums/Role.java
  src/main/java/net/causw/domain/model/enums/UserState.java
Labels: refactor, feat

#668 feat: 동아리 부원 명단 조회 기능 구현
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/application/circle/CircleService.java
Labels: feat

#670 fix : 특별한 권한을 갖는 유저 확인하는 api 500에러 해결
  src/main/java/net/causw/application/user/UserService.java
Labels: fix

#673 refactor: 게시글 검색 알고리즘 수정
  src/main/java/net/causw/adapter/persistence/repository/post/PostRepository.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/application/post/PostService.java
Labels: refactor

#672 feat : 투표 기능 구현
  src/main/java/net/causw/adapter/persistence/post/Post.java
  src/main/java/net/causw/adapter/persistence/repository/vote/VoteOptionRepository.java
  src/main/java/net/causw/adapter/persistence/repository/vote/VoteRecordRepository.java
  src/main/java/net/causw/adapter/persistence/repository/vote/VoteRepository.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/persistence/vote/Vote.java
  src/main/java/net/causw/adapter/persistence/vote/VoteOption.java
  src/main/java/net/causw/adapter/persistence/vote/VoteRecord.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/adapter/web/VoteController.java
  src/main/java/net/causw/application/dto/form/response/FormResponseDto.java
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/application/dto/post/PostsResponseDto.java
  src/main/java/net/causw/application/dto/util/StatusUtil.java
  src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
  src/main/java/net/causw/application/dto/util/dtoMapper/VoteDtoMapper.java
  src/main/java/net/causw/application/dto/vote/CastVoteRequestDto.java
  src/main/java/net/causw/application/dto/vote/CreateVoteRequestDto.java
  src/main/java/net/causw/application/dto/vote/VoteOptionResponseDto.java
  src/main/java/net/causw/application/dto/vote/VoteResponseDto.java
  src/main/java/net/causw/application/homepage/HomePageService.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/vote/VoteService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: feat

#674 Feat : 소프트웨어학부 공지사항 크롤링할 때 첨부파일 및 이미지까지 가져오기
  src/main/java/net/causw/adapter/persistence/crawled/CrawledFileLink.java
  src/main/java/net/causw/adapter/persistence/crawled/CrawledNotice.java
  src/main/java/net/causw/application/crawler/WebCrawlerService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
  src/main/java/net/causw/domain/model/util/StaticValue.java
Labels: feat

#681 Fix: Form이 Null 인 경우 NullPointer Exception이 발생하여, Null인지 검사하는 로직 추가
  src/main/java/net/causw/adapter/persistence/post/Post.java
Labels: bug

#685 hotfix: locker api들 스웨거 문서 설명 추가
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/common/CommonService.java
  src/main/java/net/causw/application/dto/locker/LockerCreateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerLocationUpdateRequestDto.java
  src/main/java/net/causw/application/dto/locker/LockerMoveRequestDto.java
  src/main/java/net/causw/application/locker/LockerService.java
Labels: hotfix

#686 refactor: 게시글 반환값에 isOwner 필드 추가
  src/main/java/net/causw/application/dto/post/PostResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
  src/main/java/net/causw/application/post/PostService.java
Labels: refactor

#688 hotfix: form validation 로직 수정 및 모듈화
  src/main/java/net/causw/adapter/persistence/form/Form.java
  src/main/java/net/causw/adapter/persistence/form/FormQuestion.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/form/request/create/FormCreateRequestDto.java
  src/main/java/net/causw/application/dto/form/request/create/OptionCreateRequestDto.java
  src/main/java/net/causw/application/dto/form/request/create/QuestionCreateRequestDto.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: hotfix

#689 hotfix: toCircleResponseDto를 사용했을 때 mainImage가 null이 되는 오류 수정
  src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java
Labels: bug, hotfix
