Repository CAUCSE/CAUSW_backend, pull requests merged in 2024-10, with the labels that each got.

#692 hotfix: form, user, login 버긋 ㅜ정
  src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordApplication.java
  src/main/java/net/causw/adapter/persistence/userAcademicRecord/UserAcademicRecordLog.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/form/FormService.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
  src/main/java/net/causw/application/uuidFile/UuidFileService.java
Labels: hotfix

#691 hotfix: 프로밀 및 증빙서류 이미지 null값 에러 수정
  src/main/java/net/causw/application/user/UserService.java
Labels: hotfix

#694 hotfix: form 접근 권한 수정 및 null 방지
  src/main/java/net/causw/adapter/persistence/form/ReplySelectedOptionManager.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/application/form/FormService.java
Labels: hotfix

#696 hotfix: 동아리 수정 시 mainImage가 null이고 현재 mainImage도 null인 경우 예외 발생
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/form/FormService.java
Labels: bug, hotfix

#697 fix: findCurrentUser 수정
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/config/security/JwtTokenProvider.java
Labels: bug, hotfix

#698 hotfix: 신청서 결과 요약 조회 시 중복 응답 가능 여부와 총 응답수를 반환하도록 변경
  src/main/java/net/causw/application/dto/form/response/QuestionSummaryResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
  src/main/java/net/causw/application/form/FormService.java
Labels: hotfix

#699 fix: circle excel export
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/util/dtoMapper/CircleDtoMapper.java
Labels: bug, hotfix, fix

#701 fix: delete user refresh token
  src/main/java/net/causw/adapter/persistence/user/User.java
Labels: hotfix, fix

#702 Hotfix : 유저서비스 트랜잭션 문제 해결
  src/main/java/net/causw/application/user/UserService.java
Labels: bug, hotfix

#703 fix: 본인 학적 신청 조회 api 수정
  src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
Labels: bug, hotfix

#704 hotfix: 학생회비 납부자 조회 시 닉네임도 조회하도록 수정
  src/main/java/net/causw/application/dto/userCouncilFee/UserCouncilFeeResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/UserCouncilFeeDtoMapper.java
  src/main/java/net/causw/application/excel/CouncilFeeExcelService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
Labels: hotfix, fix

#706 hotfix : 알림설정 여부 확인 기능 추가
  src/main/java/net/causw/adapter/web/NotificationController.java
  src/main/java/net/causw/application/notification/NotificationService.java
Labels: hotfix

#707 Fix/academic record
  src/main/java/net/causw/domain/model/enums/userAcademicRecord/AcademicStatus.java
Labels: hotfix, fix

#708 Fix/user admission
  src/main/java/net/causw/adapter/persistence/user/UserAdmission.java
  src/main/java/net/causw/adapter/persistence/user/UserAdmissionLog.java
  src/main/java/net/causw/application/user/UserService.java
Labels: hotfix, fix

#709 fix: file url lengh fix
  src/main/java/net/causw/adapter/persistence/uuidFile/UuidFile.java
Labels: hotfix, fix

#710 Fix/board
  src/main/java/net/causw/adapter/persistence/board/Board.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/dto/board/NoticeBoardCreateRequestDto.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: bug, hotfix, fix

#711 fix: create board api fix
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/dto/board/BoardCreateRequestDto.java
  src/main/java/net/causw/application/dto/board/NoticeBoardCreateRequestDto.java
  src/main/java/net/causw/domain/exceptions/ErrorCode.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: bug, hotfix, fix

#712 fix: post to board
  src/main/java/net/causw/application/post/PostService.java
Labels: bug, hotfix

#713 fix: role 버그 삭제
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/config/security/SecurityService.java
Labels: bug, hotfix, fix

#715 fix: user auth
  src/main/java/net/causw/config/security/SecurityService.java
Labels: bug, hotfix

#714 feat: 각 유저의 동아리 신청 조회 API 구현
  src/main/java/net/causw/adapter/persistence/repository/form/ReplyRepository.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/application/dto/form/response/reply/UserReplyResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
  src/main/java/net/causw/application/form/FormService.java
Labels: feat

#716 Fix/fee
  src/main/java/net/causw/adapter/persistence/repository/userCouncilFee/UserCouncilFeeRepository.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFee.java
  src/main/java/net/causw/adapter/persistence/userCouncilFee/UserCouncilFeeLog.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/userAcademicRecordApplication/UpdateUserAcademicRecordApplicationStateRequestDto.java
  src/main/java/net/causw/application/dto/userAcademicRecordApplication/UpdateUserAcademicStatusRequestDto.java
  src/main/java/net/causw/application/dto/userCouncilFee/CreateUserCouncilFeeWithUserRequestDto.java
  src/main/java/net/causw/application/dto/util/StatusUtil.java
  src/main/java/net/causw/application/form/FormService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: bug, fix

#717 refactor: 각 유저별 동아리 신청서 응답 조회시 질문도 같이 반환하도록 변경
  src/main/java/net/causw/application/dto/form/response/reply/UserReplyResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/FormDtoMapper.java
  src/main/java/net/causw/application/form/FormService.java
Labels: refactor

#718 fix: 댓글+대댓글의 수가 올바르도록 수정
  src/main/java/net/causw/adapter/persistence/repository/post/PostRepository.java
Labels: fix

#719 fix: JoinEntity OneToOne -> ManyToOne
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java
Labels: bug, hotfix, fix

#720 hotfix: 게시글 미리보기 시 썸네일을 표시하도록 변경
  src/main/java/net/causw/application/dto/post/PostsResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
  src/main/java/net/causw/application/homepage/HomePageService.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/application/user/UserService.java
Labels: hotfix, fix

#721 fix: active user 조회 에러 수정 및 join entity 수정
  src/main/java/net/causw/adapter/persistence/base/BaseEntity.java
  src/main/java/net/causw/adapter/persistence/crawled/CrawledNotice.java
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/persistence/uuidFile/UuidFile.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/CalendarAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/CircleMainImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/EventAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/JoinEntity.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/PostAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordApplicationAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordLogAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAdmissionAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAdmissionLogAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserProfileImage.java
  src/main/java/net/causw/adapter/persistence/vote/Vote.java
  src/main/java/net/causw/adapter/web/CalendarController.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/adapter/web/EventController.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/adapter/web/VoteController.java
  src/main/java/net/causw/application/calendar/CalendarService.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/dto/form/request/create/OptionCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
  src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
  src/main/java/net/causw/application/dto/userAcademicRecordApplication/UpdateUserAcademicRecordApplicationStateRequestDto.java
  src/main/java/net/causw/application/dto/userAcademicRecordApplication/UpdateUserAcademicStatusRequestDto.java
  src/main/java/net/causw/application/dto/userCouncilFee/CreateUserCouncilFeeWithUserRequestDto.java
  src/main/java/net/causw/application/dto/util/StatusUtil.java
  src/main/java/net/causw/application/dto/util/dtoMapper/PostDtoMapper.java
  src/main/java/net/causw/application/dto/vote/CastVoteRequestDto.java
  src/main/java/net/causw/application/event/EventService.java
  src/main/java/net/causw/application/excel/ExcelAbstractService.java
  src/main/java/net/causw/application/homepage/HomePageService.java
  src/main/java/net/causw/application/post/PostService.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/uuidFile/UuidFileService.java
  src/main/java/net/causw/config/security/JwtTokenProvider.java
  src/main/java/net/causw/domain/model/enums/form/FormType.java
  src/main/java/net/causw/domain/model/enums/user/UserAdmissionLogAction.java
  src/main/java/net/causw/domain/validation/GrantableRoleValidator.java
Labels: bug, refactor, hotfix, fix

#722 hotfix: 유저 삭제시 재학인증 기록, 이미지 미삭제 오류 해결
  src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
  src/main/java/net/causw/adapter/persistence/repository/uuidFile/UserAcademicRecordApplicationAttachImageRepository.java
  src/main/java/net/causw/application/user/UserService.java
Labels: bug, hotfix

#724 fix: post 썸네일 파일 이미지 파일만 적용 되게 수정
  src/main/java/net/causw/application/post/PostService.java
Labels: bug, hotfix, fix

#726 hotfix : 개인정보 수정에서 전화번호 입력 필수 -> 선택으로 변경
  src/main/java/net/causw/application/dto/user/UserUpdateRequestDto.java
Labels: hotfix

#727 fix: develop branch conflict 해결
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/persistence/vote/Vote.java
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/circle/CircleService.java
  src/main/java/net/causw/application/crawler/WebCrawlerService.java
  src/main/java/net/causw/application/excel/FormExcelService.java
  src/main/java/net/causw/application/form/FormService.java
  src/main/java/net/causw/application/locker/LockerActionRegister.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/config/security/JwtTokenProvider.java
  src/main/java/net/causw/domain/validation/UserStateValidator.java
Labels: fix

#742 hotfix: user OneToMany DB 칼럼명 오타 수정 및 Board 스웨거 오타 수정
  src/main/java/net/causw/adapter/persistence/user/User.java
  src/main/java/net/causw/adapter/web/BoardController.java
Labels: bug, docs, hotfix
