Repository CAUCSE/CAUSW_backend, pull requests merged in 2024-11, with the labels that each got.

#747 Fix : UserAdmission 쿼리문 500에러 수정 (#746)
  src/main/java/net/causw/adapter/persistence/repository/user/UserAdmissionRepository.java
Labels: bug, fix

#752 fix: uuidfile 객체 OneToOne -> ManyToOne으로 버그 픽스
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordLogAttachImage.java
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAdmissionLogAttachImage.java
Labels: bug, fix

#754 fix: user admission 버그 픽스
  src/main/java/net/causw/adapter/persistence/repository/user/UserAdmissionRepository.java
  src/main/java/net/causw/application/user/UserService.java
Labels: bug, hotfix, fix

#755 fix: User Admission API 수정
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: fix

#758 hotfix: User Academic Record Log Attach Image table 수정
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordApplicationAttachImage.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
Labels: bug, hotfix

#759 hotfix: dev to qa
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordApplicationAttachImage.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
Labels: bug, hotfix

#760 hotfix: qa to main
  src/main/java/net/causw/adapter/persistence/uuidFile/joinEntity/UserAcademicRecordApplicationAttachImage.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
Labels: bug, hotfix

#761 hotfix: board 생성 관련 api에서 circle 제대로 인식 못하는 문제 수정
  src/main/java/net/causw/adapter/persistence/board/BoardApply.java
  src/main/java/net/causw/application/board/BoardService.java
  src/main/java/net/causw/application/dto/board/NormalBoardApplyRequestDto.java
  src/main/java/net/causw/application/dto/board/NormalBoardApplyResponseDto.java
  src/main/java/net/causw/application/dto/util/dtoMapper/BoardDtoMapper.java
Labels: bug, fix

#764 fix: user admission 거절 시 user state 관리 및 user academic status 로직 수정
  src/main/java/net/causw/adapter/persistence/repository/userAcademicRecord/UserAcademicRecordApplicationRepository.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/application/userAcademicRecord/UserAcademicRecordApplicationService.java
Labels: bug, fix

#763 fix: 학생회비 등록 예외 핸들링 추가
  src/main/java/net/causw/application/semester/SemesterService.java
  src/main/java/net/causw/application/userCouncilFee/UserCouncilFeeService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: fix

#766 hotfix: locker set expiredAt request dto valid anotation 변경
  src/main/java/net/causw/application/dto/locker/LockerExpiredAtRequestDto.java
Labels: bug, hotfix

#768 hotfix: locker controller 권한 검증 로직 수정
  src/main/java/net/causw/adapter/web/LockerController.java
Labels: bug, hotfix

#769 fix : 게시글 작성자도 게시글을 삭제할 수 있도록 수정
  src/main/java/net/causw/application/post/PostService.java
Labels: fix

#770 Fix/calendar setting
  src/main/java/net/causw/adapter/web/CalendarController.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/adapter/web/EventController.java
  src/main/java/net/causw/adapter/web/PostController.java
  src/main/java/net/causw/adapter/web/StorageController.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/config/security/OctetStreamReadMsgConverter.java
  src/main/java/net/causw/config/security/WebConfig.java
Labels: fix

#771 fix: post 중복 validator 제거
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/application/post/PostService.java
Labels: bug, fix
