Repository CAUCSE/CAUSW_backend, pull requests merged in 2025-08, with the labels that each got.

#891 feat: 경조사 신청 시 알림 보낼 학번 설정
  app-main/src/main/java/net/causw/app/main/controller/CeremonyController.java
  app-main/src/main/java/net/causw/app/main/domain/model/entity/ceremony/Ceremony.java
  app-main/src/main/java/net/causw/app/main/domain/model/entity/notification/CeremonyNotificationSetting.java
  app-main/src/main/java/net/causw/app/main/domain/model/enums/ceremony/CeremonyContext.java
  app-main/src/main/java/net/causw/app/main/domain/validation/AdmissionYearsValidator.java
  app-main/src/main/java/net/causw/app/main/dto/ceremony/CeremonyNotificationSettingResponseDto.java
  app-main/src/main/java/net/causw/app/main/dto/ceremony/CeremonyResponseDto.java
  app-main/src/main/java/net/causw/app/main/dto/ceremony/CreateCeremonyNotificationSettingDto.java
  app-main/src/main/java/net/causw/app/main/dto/ceremony/CreateCeremonyRequestDto.java
  app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/CeremonyDtoMapper.java
  app-main/src/main/java/net/causw/app/main/repository/notification/CeremonyNotificationSettingRepository.java
  app-main/src/main/java/net/causw/app/main/service/ceremony/CeremonyService.java
  app-main/src/main/java/net/causw/app/main/service/notification/CeremonyNotificationService.java
  app-main/src/main/resources/db/migration/V20250730144424__AddCeremonyTarget.sql
  app-main/src/test/java/net/causw/app/main/service/notification/CeremonyNotificationServiceTest.java
  global/src/main/java/net/causw/global/constant/MessageUtil.java
Labels: feat

#895 hotfix: 카테고리 enum 누락 해결
  app-main/src/main/resources/db/migration/V20250803171739__add_graduation_to_ceremony_category_enum.sql
Labels: fix

#904 fix: 경조사 관리 목록 정렬 & 내 경조사 목록 정렬 및 DTO 수정
  app-main/src/main/java/net/causw/app/main/controller/CeremonyController.java
  app-main/src/main/java/net/causw/app/main/dto/notification/CeremonyListNotificationDto.java
  app-main/src/main/java/net/causw/app/main/dto/util/dtoMapper/NotificationDtoMapper.java
  app-main/src/main/java/net/causw/app/main/repository/ceremony/CeremonyRepository.java
  app-main/src/main/java/net/causw/app/main/service/ceremony/CeremonyService.java
Labels: fix

#901 bug: 경조사 알림 최초 설정 오류 해결
  app-main/src/main/java/net/causw/app/main/dto/ceremony/CreateCeremonyNotificationSettingDto.java
  app-main/src/main/java/net/causw/app/main/repository/notification/CeremonyNotificationSettingRepository.java
  app-main/src/main/java/net/causw/app/main/service/userAcademicRecord/UserAcademicRecordApplicationService.java
  app-main/src/main/resources/db/migration/V20250809015435__CreateDefaultCeremonyNotificationSettings.sql
Labels: bug

#923 fix: 즐겨찾기 취소 오류 해결 및 개선
  app-main/src/main/java/net/causw/app/main/domain/model/entity/post/FavoritePost.java
  app-main/src/main/java/net/causw/app/main/repository/post/FavoritePostRepository.java
  app-main/src/main/java/net/causw/app/main/service/homepage/HomePageService.java
  app-main/src/main/java/net/causw/app/main/service/post/PostService.java
  app-main/src/main/java/net/causw/app/main/service/user/UserService.java
  app-main/src/main/resources/db/migration/V20250816001721__RemoveIsDeleteFromFavoritePost.sql
  app-main/src/test/java/net/causw/app/main/service/user/UserServiceTest.java
  global/src/main/java/net/causw/global/constant/MessageUtil.java
Labels: bug

#925 fix: 동문수첩 프로필 목록 비활성 유저 필터링
  app-main/src/main/java/net/causw/app/main/repository/userInfo/UserInfoRepository.java
  app-main/src/main/java/net/causw/app/main/service/userInfo/UserInfoService.java
  global/src/main/java/net/causw/global/constant/MessageUtil.java
Labels: bug
