Repository CAUCSE/CAUSW_backend, pull requests merged in 2025-01, with the labels that each got.

#775 fix: 회원가입 API 유효하지 않은 요청 예외처리 추가
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/domain/model/util/MessageUtil.java
Labels: bug

#776 fix: Role 검사 로직 통합(SecurityService)
  src/main/java/net/causw/adapter/web/BoardController.java
  src/main/java/net/causw/adapter/web/CalendarController.java
  src/main/java/net/causw/adapter/web/CircleController.java
  src/main/java/net/causw/adapter/web/CommonController.java
  src/main/java/net/causw/adapter/web/EventController.java
  src/main/java/net/causw/adapter/web/FormController.java
  src/main/java/net/causw/adapter/web/LockerController.java
  src/main/java/net/causw/adapter/web/SemesterController.java
  src/main/java/net/causw/adapter/web/StorageController.java
  src/main/java/net/causw/adapter/web/UserAcademicRecordApplicationController.java
  src/main/java/net/causw/adapter/web/UserController.java
  src/main/java/net/causw/adapter/web/UserCouncilFeeController.java
  src/main/java/net/causw/config/security/SecurityService.java
Labels: refactor, fix

#745 Fix : 전화번호 형식 변경 및 validation 적용
  src/main/java/net/causw/application/dto/user/UserCreateRequestDto.java
  src/main/java/net/causw/application/user/UserService.java
  src/main/java/net/causw/domain/validation/PhoneNumberFormatValidator.java
Labels: fix
